name: linting, testing and building
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
    push:
        branches: [main]
    pull_request: 
        branches: [main]
jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy: 
            matrix:
                node-version: [22.x]
        steps:
        - uses: actions/checkout@v4
          with:
           fetch-depth: 0
        - name: Staring Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: npm
        - name: install modules
          run: npm ci
        - name: make build production project
          run: npm run build:prod
        - name: typescript listing
          if: always()
          run: npm run lint
        - name: scss listing
          if: always()
          run: npm run lint:scss
        - name: unit testing
          if: always()
          run: npm run test:unit:run
        - name: Build Storybook
          run: npm run build-storybook
        - name: screenshot testing chromatic
          if: always()
          uses: chromaui/action@latest
          with:
           projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
           buildScriptName: 'build-storybook'
        

 
